name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the following details to help us diagnose the problem efficiently.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: dropdown
    id: Build Type
    attributes:
      label: What's your build type?
      multiple: true
      options:
        - Maven
        - Gradle

  - type: text
    id: Java Version
    attributes:
      label: What's your Java version?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log statements or stracktrace in case of exceptions
      description: Please copy and paste any relevant log statement. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful, such as screenshots, related issues, or how often it occurs.
      render: shell
